"""
Wrapper class for a document chunk.

This class acts as a wrapper for a document chunk, generated from a text file as a str by the document_chunker module.

Args: 
    id (str): an id generated by the document_chunker module on the form "filename-index".
    content (str): the raw text of the chunk.
"""

class DocChunk: 


    
    def __init__(self, id : str, content : str): 
        self.id = id
        self.content = content
        self.vector = [] 
        
        
    
    def get_id(self)-> str:
        """Returns the id of the chunk"""
        return self.id 
    
    def get_vector(self) -> list[float]:
        """Returns the vector of the DocChunk""" 
        return self.vector 
        

    def get_content(self)-> str: 
        """Return the raw text as a str"""
        return self.content
    
    def set_vector(self, vector: list[float])-> None: 
        """sets the vector""" 
        self.vector = vector 